### ISSUE TITLE
Not able to reproduce the result

### ISSUE THREAD

**Issue by mzy2240** [qingchen3/D-tree#1]
Hi! Do you mind to explain how the following code works?
```python
    G_adj = defaultdict(set) # empty dict

    spanningtree, tree_edges, non_tree_edges = constructST_adjacency_list(G_adj, 0)  # why G_adj becomes a graph or adjacency matrix here?
``` 
The above code comes from your `evaluate_insertion_only.py` file, and supposes to invoke the function from `tree_utils.py`. Unfortunately, in that `constructST_adjacency_list` function, if I understand correctly, the first argument must be a type of data describing the graph, instead of an empty dict.

**Comment by qingchen3** [comment]
Hi, 

In short, you are right. 

The setup for experiments is not described in the code.  **We started with an empty graph**. That's why you see G_adj is an empty dict, i.e., empty graph in adjacency list representation. Our codes should also work for non-empty graphs where G_adj is not an empty dict.

Best regards,
Qing

**Comment by mzy2240** [comment]
Thank you for the reply! Then what is the key and value in this G_adj dictionary? Most of the time when we talk about adjacency matrix for large scale system, it would be in a sparse matrix format with nonzeros (normally 1) indicating the connection between two vertices.
